### ISSUE TITLE
1.0.0-1.19.4 not being loaded

### ISSUE THREAD

**Issue by LessThanBenji** [Totobird-Creations/Configurable-Nether-Portals-Mod#1]
Hi, sorry to be a downer, but the mod doesn't appear to be working at all. I'm trying to load it in 1.19.4 with Fabric 0.14.21 and Fabric API 0.85.0, but the mod isn't being detected at all. It won't even appear in the logs at all, as an error or a notice or otherwise. Let me know if you need any logs :)

**Comment by Totobird-Creations** [comment]
Hello. Are you using the 1.19.4 version, and did you check if the gamerules are there?

**Comment by LessThanBenji** [comment]
Correct, I'm using 1.0.0 (the 1.19.4 version), and yes the gamerules were not there. I even tried typing them out in chat, tab didn't autofill them and they weren't recognized.

**Comment by Totobird-Creations** [comment]
Can I see a mod list?

**Comment by LessThanBenji** [comment]
Only fabric-api-0.85.0+1.19.4 and confnportal-1.0.0. No mods besides that.

**Comment by Totobird-Creations** [comment]
This probably isn't the issue, but it might be worth looking at. I tested this mod using fabric api ~~`0.86.0`~~ (edit. I wrote the wrong version. It should have been `0.84.x`, though it shouldn't matter), wheras you used `0.85.0`.
Could you try running this with a later version of fabric api?

**Comment by LessThanBenji** [comment]
Still not working with 0.86.0. Fabric API 0.86.0 was only released today and is a beta version, are you sure you meant that version? It's just I see the mod's been live for a month already, meaning you must've tested it with 0.84.0 or earlier.

**Comment by Totobird-Creations** [comment]
Can you attach the jar file for confnportal, as well as any logs?

**Comment by LessThanBenji** [comment]
https://www.dropbox.com/sh/w1tig3mll2llgiy/AADQwjMTq-s0rXs-rbojAU6va?dl=1

The above link will provide you a .zip with my confnportal jar and the relevant log.

**Comment by Totobird-Creations** [comment]
Okay. I am pretty sure that have figured out what the problem is.
The `fabric.mod.json` file contains a key called `environment`, which I had set to `server`. I thought that this was just a marker to show that it's a server-side mod, but it turns out that it completely prevents the mod from loading on a client. This probably means my better totems mod is also broken.

Confnportal should now be fixed on Modrinth under versions `1.1.0-1.19.4` and `1.1.0-1.20.1`.
*Edit: Better-Totems should now be fixed on Modrinth under versions `1.1.0-1.19.4` and `1.1.0-1.20.1`*

**Comment by LessThanBenji** [comment]
I've just tested both of them out, working perfectly fine now. Thank you so much, nice job!
